"""Auto sync models

Revision ID: 29830fc93a69
Revises: 97ab3e0a7937
Create Date: 2026-04-21 15:42:43.396008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29830fc93a69'
down_revision: Union[str, Sequence[str], None] = '97ab3e0a7937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'is_active')
    # ### end Alembic commands ###
